### ISSUE TITLE
Central Management - Service - Installation in French locale fails

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/chocolatey-licensed-issues#166] opened 2020-07-27 18:10 UTC
When attempting to perform the installation of central-management-service on a french system, the installation throws an error when starting installing/starting the service.

# References

[Internal Issue](https://gitlab.com/chocolatey/choco-licensed-management-ui/-/issues/431)

**Comment by ferventcoder** [comment] 2020-10-23 12:22
This was fixed and released with Central Management v0.3.1.

**Closed by ferventcoder** 2020-10-23 12:22 UTC
Labels: 0 - _Triaging, Bug, CentralManagement

**Comment by ferventcoder** [comment] 2020-10-23 12:23
This was determined to be a duplicate of #174
