### ISSUE TITLE
Choco download command ignores --no-progress switch

### ISSUE THREAD

**Issue by peterbarendse** [chocolatey/chocolatey-licensed-issues#149] opened 2020-06-15 20:58 UTC
### What You Are Seeing?
Choco download <package> command ignores --no-progress switch. Also the 'choco feature disable -n=showDownloadProgress' doesn't solve the issue.

### What is Expected?
That choco download <package> download progress can be disabled. It generates massive log files.

### How Did You Get This To Happen? (Steps to Reproduce)
run: choco download <package> --no-progress

**Comment by ferventcoder** [comment] 2020-06-15 20:58
Duplicate of #104

**Closed** 2020-06-15 20:58 UTC
