### ISSUE TITLE
sync command / Package Builder - Illegal characters in Support URL cause package not to be created

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/chocolatey-licensed-issues#111] opened 2019-10-18 19:51 UTC
### What You Are Seeing?

Try to create a package whose projectUrl from the installer is invalid.

Nessus Agent example output:

The 'http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd:projectUrl' eleme
nt is invalid - The value 'http://www.Tenable,Inc..com' is invalid according to
its datatype 'http://www.w3.org/2001/XMLSchema:anyURI' - The string 'http://www.
Tenable,Inc..com' is not a valid Uri value.

## Other Information

* Chocolatey Version - 0.10.15
* Chocolatey.Extension Version - 2.0.2

### What is Expected?

The URL should be captured, and either sanitzed, or skipped, and a TODO item generated for the Nuspec

**Comment by ferventcoder** [comment] 2019-10-20 14:17
This could be a duplicate of #109

**Comment by ferventcoder** [comment] 2020-05-18 19:58
This has been fixed and will be released in Chocolatey Licensed Extension v2.1.0.

**Closed by ferventcoder** 2020-05-18 19:58 UTC
Labels: 3 - Done, Bug, Edition - Business, LicensedExtension, Priority_HIGH
