### ISSUE TITLE
Package Internalizer - Using --version to choose version to internalize causes dependencies to build with that same version

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/chocolatey-licensed-issues#180] opened 2020-09-30 19:41 UTC
Example:

`choco.exe download --limit-output --Source https://chocolatey.org/api/v2/ --Internalize --version 15.0.18338.0 --downloadCache --Name sql-server-management-studio --force -y --no-progress` causes all nupkgs to be tagged with the version from the command.

## References

[Internal Issue](https://gitlab.com/chocolatey/collaborators/choco-licensed/-/issues/359)

**Comment by steviecoaster** [comment] 2020-10-01 12:19
This is fixed already here: https://github.com/chocolatey/chocolatey-licensed-issues/issues/44. 

If you are running into this issue, upgrade your licensed extension to 1.12.12 or higher.

**Comment by ferventcoder** [comment] 2020-10-01 19:56
Duplicate of #44

**Closed by ferventcoder** 2020-10-01 19:56 UTC
Labels: Duplicate
